version: '3.8'
services:
  db:
    image: postgres:15
    container_name: test-postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
      # another way to use volume on host
      # - my-postgres.conf":/etc/postgresql/postgresql.conf
volumes:
  db:
    driver: local